// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 98sZpX3o3cqNhorsdtcuRP
// Component: fuhQ_AMpco
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_blank_project_mobile_first.module.css"; // plasmic-import: 98sZpX3o3cqNhorsdtcuRP/projectcss
import sty from "./PlasmicGeoSvg.module.css"; // plasmic-import: fuhQ_AMpco/css
import GeosvgIcon from "./icons/PlasmicIcon__Geosvg"; // plasmic-import: m3jK-J1WY/icon

export const PlasmicGeoSvg__VariantProps = new Array();

export const PlasmicGeoSvg__ArgProps = new Array();

function PlasmicGeoSvg__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <GeosvgIcon
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_tokens,
        sty.root
      )}
      role={"img"}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicGeoSvg__ArgProps,
      internalVariantPropNames: PlasmicGeoSvg__VariantProps
    });

    return PlasmicGeoSvg__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicGeoSvg";
  } else {
    func.displayName = `PlasmicGeoSvg.${nodeName}`;
  }
  return func;
}

export const PlasmicGeoSvg = Object.assign(
  // Top-level PlasmicGeoSvg renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicGeoSvg
    internalVariantProps: PlasmicGeoSvg__VariantProps,
    internalArgProps: PlasmicGeoSvg__ArgProps
  }
);

export default PlasmicGeoSvg;
/* prettier-ignore-end */
