// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 98sZpX3o3cqNhorsdtcuRP
// Component: I6qO5BgoqM
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_blank_project_mobile_first.module.css"; // plasmic-import: 98sZpX3o3cqNhorsdtcuRP/projectcss
import sty from "./PlasmicMaPosition.module.css"; // plasmic-import: I6qO5BgoqM/css
import Searchsvg2Icon from "./icons/PlasmicIcon__Searchsvg2"; // plasmic-import: 8R8e7nHTx/icon
import GeosvgIcon from "./icons/PlasmicIcon__Geosvg"; // plasmic-import: m3jK-J1WY/icon
import ClockHistorysvgIcon from "./icons/PlasmicIcon__ClockHistorysvg"; // plasmic-import: 3jSeOuvz6/icon
import ListsvgIcon from "./icons/PlasmicIcon__Listsvg"; // plasmic-import: xFxMcfslv/icon
import Starsvg2Icon from "./icons/PlasmicIcon__Starsvg2"; // plasmic-import: sIXlj-e3g/icon

export const PlasmicMaPosition__VariantProps = new Array();

export const PlasmicMaPosition__ArgProps = new Array();

function PlasmicMaPosition__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"maPosition"}
            data-plasmic-override={overrides.maPosition}
            className={classNames(projectcss.all, sty.maPosition)}
          >
            <div
              data-plasmic-name={"frame2"}
              data-plasmic-override={overrides.frame2}
              className={classNames(projectcss.all, sty.frame2)}
            >
              <div
                data-plasmic-name={"freePark"}
                data-plasmic-override={overrides.freePark}
                className={classNames(projectcss.all, sty.freePark)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__p90Nn
                  )}
                >
                  {"FreePark"}
                </div>
              </div>
            </div>

            <div
              data-plasmic-name={"frame6"}
              data-plasmic-override={overrides.frame6}
              className={classNames(projectcss.all, sty.frame6)}
            >
              <div
                data-plasmic-name={"frame7"}
                data-plasmic-override={overrides.frame7}
                className={classNames(projectcss.all, sty.frame7)}
              >
                <div
                  data-plasmic-name={"maPositionActuelle"}
                  data-plasmic-override={overrides.maPositionActuelle}
                  className={classNames(projectcss.all, sty.maPositionActuelle)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__re9VH
                    )}
                  >
                    {"Ma position actuelle"}
                  </div>
                </div>
              </div>

              <div
                data-plasmic-name={"image1"}
                data-plasmic-override={overrides.image1}
                className={classNames(projectcss.all, sty.image1)}
              />
            </div>

            <div
              data-plasmic-name={"frame5"}
              data-plasmic-override={overrides.frame5}
              className={classNames(projectcss.all, sty.frame5)}
            >
              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link___7LhDt
                )}
                href={"/mes-dernieres-recherches"}
              >
                <Searchsvg2Icon
                  className={classNames(projectcss.all, sty.svg__j5QTu)}
                  role={"img"}
                />
              </a>

              <GeosvgIcon
                className={classNames(projectcss.all, sty.svg___4FmvL)}
                role={"img"}
              />

              <ClockHistorysvgIcon
                className={classNames(projectcss.all, sty.svg__jQQjR)}
                role={"img"}
              />

              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link___1J7Ns
                )}
                href={"/menu"}
              >
                <ListsvgIcon
                  className={classNames(projectcss.all, sty.svg__c1AVf)}
                  role={"img"}
                />
              </a>

              <Starsvg2Icon
                className={classNames(projectcss.all, sty.svg__qcV4)}
                role={"img"}
              />
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "maPosition",
    "frame2",
    "freePark",
    "frame6",
    "frame7",
    "maPositionActuelle",
    "image1",
    "frame5"
  ],

  maPosition: [
    "maPosition",
    "frame2",
    "freePark",
    "frame6",
    "frame7",
    "maPositionActuelle",
    "image1",
    "frame5"
  ],

  frame2: ["frame2", "freePark"],
  freePark: ["freePark"],
  frame6: ["frame6", "frame7", "maPositionActuelle", "image1"],
  frame7: ["frame7", "maPositionActuelle"],
  maPositionActuelle: ["maPositionActuelle"],
  image1: ["image1"],
  frame5: ["frame5"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMaPosition__ArgProps,
      internalVariantPropNames: PlasmicMaPosition__VariantProps
    });

    return PlasmicMaPosition__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMaPosition";
  } else {
    func.displayName = `PlasmicMaPosition.${nodeName}`;
  }
  return func;
}

export const PlasmicMaPosition = Object.assign(
  // Top-level PlasmicMaPosition renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    maPosition: makeNodeComponent("maPosition"),
    frame2: makeNodeComponent("frame2"),
    freePark: makeNodeComponent("freePark"),
    frame6: makeNodeComponent("frame6"),
    frame7: makeNodeComponent("frame7"),
    maPositionActuelle: makeNodeComponent("maPositionActuelle"),
    image1: makeNodeComponent("image1"),
    frame5: makeNodeComponent("frame5"),
    // Metadata about props expected for PlasmicMaPosition
    internalVariantProps: PlasmicMaPosition__VariantProps,
    internalArgProps: PlasmicMaPosition__ArgProps
  }
);

export default PlasmicMaPosition;
/* prettier-ignore-end */
