// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 98sZpX3o3cqNhorsdtcuRP
// Component: cgySl3z9Tl
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import TextInput from "../../TextInput"; // plasmic-import: Lqi7nqTyENV/component
import { useScreenVariants as useScreenVariants_9Br8OmEmlKp } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 9Br8OmEMLKp/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_blank_project_mobile_first.module.css"; // plasmic-import: 98sZpX3o3cqNhorsdtcuRP/projectcss
import sty from "./Plasmic_5RechercheUnePlace.module.css"; // plasmic-import: cgySl3z9Tl/css
import Group3Icon from "./icons/PlasmicIcon__Group3"; // plasmic-import: bA1IDYE7Ge2/icon
import Line7Icon from "./icons/PlasmicIcon__Line7"; // plasmic-import: Nf7EEJMjGTg/icon
import StarFillsvgIcon from "./icons/PlasmicIcon__StarFillsvg"; // plasmic-import: XNTxjHm25/icon
import Starsvg2Icon from "./icons/PlasmicIcon__Starsvg2"; // plasmic-import: sIXlj-e3g/icon
import Searchsvg2Icon from "./icons/PlasmicIcon__Searchsvg2"; // plasmic-import: 8R8e7nHTx/icon
import GeosvgIcon from "./icons/PlasmicIcon__Geosvg"; // plasmic-import: m3jK-J1WY/icon
import ClockHistorysvgIcon from "./icons/PlasmicIcon__ClockHistorysvg"; // plasmic-import: 3jSeOuvz6/icon
import ListsvgIcon from "./icons/PlasmicIcon__Listsvg"; // plasmic-import: xFxMcfslv/icon

export const Plasmic_5RechercheUnePlace__VariantProps = new Array();

export const Plasmic_5RechercheUnePlace__ArgProps = new Array();

function Plasmic_5RechercheUnePlace__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_9Br8OmEmlKp()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"mesDernieresRecherches"}
            data-plasmic-override={overrides.mesDernieresRecherches}
            className={classNames(projectcss.all, sty.mesDernieresRecherches)}
          >
            <div
              data-plasmic-name={"frame2"}
              data-plasmic-override={overrides.frame2}
              className={classNames(projectcss.all, sty.frame2)}
            >
              <div
                data-plasmic-name={"freePark"}
                data-plasmic-override={overrides.freePark}
                className={classNames(projectcss.all, sty.freePark)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uSxHd
                  )}
                >
                  {"FreePark"}
                </div>
              </div>
            </div>

            <div
              data-plasmic-name={"frame6"}
              data-plasmic-override={overrides.frame6}
              className={classNames(projectcss.all, sty.frame6)}
            >
              <div
                data-plasmic-name={"frame7"}
                data-plasmic-override={overrides.frame7}
                className={classNames(projectcss.all, sty.frame7)}
              >
                <div
                  data-plasmic-name={"mesDernieresRecherches2"}
                  data-plasmic-override={overrides.mesDernieresRecherches2}
                  className={classNames(
                    projectcss.all,
                    sty.mesDernieresRecherches2
                  )}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yzRpp
                    )}
                  >
                    {"Mes dernières recherches"}
                  </div>
                </div>

                <Group3Icon
                  className={classNames(projectcss.all, sty.svg__ktvrs)}
                  role={"img"}
                />
              </div>

              <Line7Icon
                className={classNames(projectcss.all, sty.svg__gmPm)}
                role={"img"}
              />

              <div
                data-plasmic-name={"_2RueTruc59000Lille"}
                data-plasmic-override={overrides._2RueTruc59000Lille}
                className={classNames(projectcss.all, sty._2RueTruc59000Lille)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ay5D2
                  )}
                >
                  {"164 Av. Willy Brandt, 59000 Lille"}
                </div>
              </div>

              <div
                data-plasmic-name={"_2BoulevardJeNeSaisPas75016Paris"}
                data-plasmic-override={
                  overrides._2BoulevardJeNeSaisPas75016Paris
                }
                className={classNames(
                  projectcss.all,
                  sty._2BoulevardJeNeSaisPas75016Paris
                )}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ypnHn
                  )}
                >
                  {"5 Avenue du Peuple Belge 59800 Lille"}
                </div>
              </div>

              <StarFillsvgIcon
                className={classNames(projectcss.all, sty.svg__nfY7G)}
                role={"img"}
              />

              <Starsvg2Icon
                className={classNames(projectcss.all, sty.svg__d24WS)}
                role={"img"}
              />
            </div>

            <div
              data-plasmic-name={"frame5"}
              data-plasmic-override={overrides.frame5}
              className={classNames(projectcss.all, sty.frame5)}
            >
              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__h5Zkp
                )}
                href={"/mes-dernieres-recherches"}
              >
                <Searchsvg2Icon
                  className={classNames(projectcss.all, sty.svg__wCYi3)}
                  role={"img"}
                />
              </a>

              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__ienEl
                )}
                href={"/ma-position"}
              >
                <GeosvgIcon
                  className={classNames(projectcss.all, sty.svg__lvqfM)}
                  role={"img"}
                />
              </a>

              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__jkeP4
                )}
              >
                <a
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__iZahm
                  )}
                  href={"/mes-dernieres-recherches"}
                >
                  <ClockHistorysvgIcon
                    className={classNames(projectcss.all, sty.svg__tBxVo)}
                    role={"img"}
                  />
                </a>
              </a>

              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__wF3Kq
                )}
                href={"/menu"}
              >
                <ListsvgIcon
                  className={classNames(projectcss.all, sty.svg__wmAeo)}
                  role={"img"}
                />
              </a>

              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link___64N9P
                )}
                href={"/favoris"}
              >
                <Starsvg2Icon
                  className={classNames(projectcss.all, sty.svg___3BSwk)}
                  role={"img"}
                />
              </a>
            </div>

            <TextInput
              className={classNames("__wab_instance", sty.textInput___4KNfp)}
              placeholder={"  Numéro de rue, code postal ou ville... "}
              showStartIcon={true}
            />

            <TextInput
              className={classNames("__wab_instance", sty.textInput___0G0WH)}
              defaultValue={"2KM"}
              placeholder={""}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mWLq
              )}
            >
              {"Distance paramétré  : "}
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "mesDernieresRecherches",
    "frame2",
    "freePark",
    "frame6",
    "frame7",
    "mesDernieresRecherches2",
    "_2RueTruc59000Lille",
    "_2BoulevardJeNeSaisPas75016Paris",
    "frame5"
  ],

  mesDernieresRecherches: [
    "mesDernieresRecherches",
    "frame2",
    "freePark",
    "frame6",
    "frame7",
    "mesDernieresRecherches2",
    "_2RueTruc59000Lille",
    "_2BoulevardJeNeSaisPas75016Paris",
    "frame5"
  ],

  frame2: ["frame2", "freePark"],
  freePark: ["freePark"],
  frame6: [
    "frame6",
    "frame7",
    "mesDernieresRecherches2",
    "_2RueTruc59000Lille",
    "_2BoulevardJeNeSaisPas75016Paris"
  ],

  frame7: ["frame7", "mesDernieresRecherches2"],
  mesDernieresRecherches2: ["mesDernieresRecherches2"],
  _2RueTruc59000Lille: ["_2RueTruc59000Lille"],
  _2BoulevardJeNeSaisPas75016Paris: ["_2BoulevardJeNeSaisPas75016Paris"],
  frame5: ["frame5"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: Plasmic_5RechercheUnePlace__ArgProps,
      internalVariantPropNames: Plasmic_5RechercheUnePlace__VariantProps
    });

    return Plasmic_5RechercheUnePlace__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "Plasmic_5RechercheUnePlace";
  } else {
    func.displayName = `Plasmic_5RechercheUnePlace.${nodeName}`;
  }
  return func;
}

export const Plasmic_5RechercheUnePlace = Object.assign(
  // Top-level Plasmic_5RechercheUnePlace renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    mesDernieresRecherches: makeNodeComponent("mesDernieresRecherches"),
    frame2: makeNodeComponent("frame2"),
    freePark: makeNodeComponent("freePark"),
    frame6: makeNodeComponent("frame6"),
    frame7: makeNodeComponent("frame7"),
    mesDernieresRecherches2: makeNodeComponent("mesDernieresRecherches2"),
    _2RueTruc59000Lille: makeNodeComponent("_2RueTruc59000Lille"),
    _2BoulevardJeNeSaisPas75016Paris: makeNodeComponent(
      "_2BoulevardJeNeSaisPas75016Paris"
    ),

    frame5: makeNodeComponent("frame5"),
    // Metadata about props expected for Plasmic_5RechercheUnePlace
    internalVariantProps: Plasmic_5RechercheUnePlace__VariantProps,
    internalArgProps: Plasmic_5RechercheUnePlace__ArgProps
  }
);

export default Plasmic_5RechercheUnePlace;
/* prettier-ignore-end */
