// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 98sZpX3o3cqNhorsdtcuRP
// Component: EafHuq3iLn
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import GeoSvg from "../../GeoSvg"; // plasmic-import: fuhQ_AMpco/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_blank_project_mobile_first.module.css"; // plasmic-import: 98sZpX3o3cqNhorsdtcuRP/projectcss
import sty from "./Plasmic_9Favoris.module.css"; // plasmic-import: EafHuq3iLn/css
import ChevronDownsvgIcon from "./icons/PlasmicIcon__ChevronDownsvg"; // plasmic-import: 8BSl9jc4D9_/icon
import Line7Icon from "./icons/PlasmicIcon__Line7"; // plasmic-import: Nf7EEJMjGTg/icon
import StarFillsvgIcon from "./icons/PlasmicIcon__StarFillsvg"; // plasmic-import: XNTxjHm25/icon
import Searchsvg2Icon from "./icons/PlasmicIcon__Searchsvg2"; // plasmic-import: 8R8e7nHTx/icon
import ClockHistorysvgIcon from "./icons/PlasmicIcon__ClockHistorysvg"; // plasmic-import: 3jSeOuvz6/icon
import ListsvgIcon from "./icons/PlasmicIcon__Listsvg"; // plasmic-import: xFxMcfslv/icon
import Starsvg2Icon from "./icons/PlasmicIcon__Starsvg2"; // plasmic-import: sIXlj-e3g/icon

export const Plasmic_9Favoris__VariantProps = new Array();

export const Plasmic_9Favoris__ArgProps = new Array("favorisProp");

function Plasmic_9Favoris__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"favoris"}
            data-plasmic-override={overrides.favoris}
            className={classNames(projectcss.all, sty.favoris)}
          >
            <div
              data-plasmic-name={"frame2"}
              data-plasmic-override={overrides.frame2}
              className={classNames(projectcss.all, sty.frame2)}
            >
              <div
                data-plasmic-name={"freePark"}
                data-plasmic-override={overrides.freePark}
                className={classNames(projectcss.all, sty.freePark)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hDpEo
                  )}
                >
                  {"FreePark"}
                </div>
              </div>
            </div>

            <div
              data-plasmic-name={"frame6"}
              data-plasmic-override={overrides.frame6}
              className={classNames(projectcss.all, sty.frame6)}
            >
              <div
                data-plasmic-name={"frame7"}
                data-plasmic-override={overrides.frame7}
                className={classNames(projectcss.all, sty.frame7)}
              >
                <div
                  data-plasmic-name={"mesAdressesFavorites"}
                  data-plasmic-override={overrides.mesAdressesFavorites}
                  className={classNames(
                    projectcss.all,
                    sty.mesAdressesFavorites
                  )}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lPDu7
                    )}
                  >
                    {"Mes adresses favorites"}
                  </div>
                </div>

                <ChevronDownsvgIcon
                  className={classNames(projectcss.all, sty.svg__n4GmC)}
                  role={"img"}
                />
              </div>

              <Line7Icon
                className={classNames(projectcss.all, sty.svg__kGiU9)}
                role={"img"}
              />

              <Line7Icon
                className={classNames(projectcss.all, sty.svg__ioSig)}
                role={"img"}
              />

              <div
                data-plasmic-name={"_2RueTruc59000Lille"}
                data-plasmic-override={overrides._2RueTruc59000Lille}
                className={classNames(projectcss.all, sty._2RueTruc59000Lille)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hVoof
                  )}
                >
                  {"33 Pl. du Général de Gaulle 59000 Lille"}
                </div>
              </div>

              <div
                data-plasmic-name={"_2BoulevardJeNeSaisPas75016Paris"}
                data-plasmic-override={
                  overrides._2BoulevardJeNeSaisPas75016Paris
                }
                className={classNames(
                  projectcss.all,
                  sty._2BoulevardJeNeSaisPas75016Paris
                )}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1VlSx
                  )}
                >
                  {"19 Pl. Pierre Mendès France 59000 Lille"}
                </div>
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___1G7Ks
                )}
              >
                {"2 rue du faubourg des postes\n59000 Lille"}
              </div>

              <StarFillsvgIcon
                className={classNames(projectcss.all, sty.svg__tUs82)}
                role={"img"}
              />

              <StarFillsvgIcon
                className={classNames(projectcss.all, sty.svg__u1RVd)}
                role={"img"}
              />

              <StarFillsvgIcon
                className={classNames(projectcss.all, sty.svg__qkrbz)}
                role={"img"}
              />
            </div>

            <div
              data-plasmic-name={"frame5"}
              data-plasmic-override={overrides.frame5}
              className={classNames(projectcss.all, sty.frame5)}
            >
              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__fHSx1
                )}
                href={"/mes-dernieres-recherches"}
              >
                <Searchsvg2Icon
                  className={classNames(projectcss.all, sty.svg___8MpCr)}
                  role={"img"}
                />
              </a>

              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__jsasU
                )}
                href={"/ma-position"}
              >
                <GeoSvg
                  data-plasmic-name={"geoSvg"}
                  data-plasmic-override={overrides.geoSvg}
                  className={classNames("__wab_instance", sty.geoSvg)}
                />
              </a>

              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__ho2Qq
                )}
                href={"/mes-dernieres-recherches"}
              >
                <ClockHistorysvgIcon
                  className={classNames(projectcss.all, sty.svg___99VKc)}
                  role={"img"}
                />
              </a>

              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__dJ3Bc
                )}
                href={"/menu"}
              >
                <ListsvgIcon
                  className={classNames(projectcss.all, sty.svg__gCnHs)}
                  role={"img"}
                />
              </a>

              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link___4RhL1
                )}
                href={"/favoris"}
              >
                <Starsvg2Icon
                  className={classNames(projectcss.all, sty.svg__ff0Kr)}
                  role={"img"}
                />
              </a>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "favoris",
    "frame2",
    "freePark",
    "frame6",
    "frame7",
    "mesAdressesFavorites",
    "_2RueTruc59000Lille",
    "_2BoulevardJeNeSaisPas75016Paris",
    "frame5",
    "geoSvg"
  ],

  favoris: [
    "favoris",
    "frame2",
    "freePark",
    "frame6",
    "frame7",
    "mesAdressesFavorites",
    "_2RueTruc59000Lille",
    "_2BoulevardJeNeSaisPas75016Paris",
    "frame5",
    "geoSvg"
  ],

  frame2: ["frame2", "freePark"],
  freePark: ["freePark"],
  frame6: [
    "frame6",
    "frame7",
    "mesAdressesFavorites",
    "_2RueTruc59000Lille",
    "_2BoulevardJeNeSaisPas75016Paris"
  ],

  frame7: ["frame7", "mesAdressesFavorites"],
  mesAdressesFavorites: ["mesAdressesFavorites"],
  _2RueTruc59000Lille: ["_2RueTruc59000Lille"],
  _2BoulevardJeNeSaisPas75016Paris: ["_2BoulevardJeNeSaisPas75016Paris"],
  frame5: ["frame5", "geoSvg"],
  geoSvg: ["geoSvg"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: Plasmic_9Favoris__ArgProps,
      internalVariantPropNames: Plasmic_9Favoris__VariantProps
    });

    return Plasmic_9Favoris__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "Plasmic_9Favoris";
  } else {
    func.displayName = `Plasmic_9Favoris.${nodeName}`;
  }
  return func;
}

export const Plasmic_9Favoris = Object.assign(
  // Top-level Plasmic_9Favoris renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    favoris: makeNodeComponent("favoris"),
    frame2: makeNodeComponent("frame2"),
    freePark: makeNodeComponent("freePark"),
    frame6: makeNodeComponent("frame6"),
    frame7: makeNodeComponent("frame7"),
    mesAdressesFavorites: makeNodeComponent("mesAdressesFavorites"),
    _2RueTruc59000Lille: makeNodeComponent("_2RueTruc59000Lille"),
    _2BoulevardJeNeSaisPas75016Paris: makeNodeComponent(
      "_2BoulevardJeNeSaisPas75016Paris"
    ),

    frame5: makeNodeComponent("frame5"),
    geoSvg: makeNodeComponent("geoSvg"),
    // Metadata about props expected for Plasmic_9Favoris
    internalVariantProps: Plasmic_9Favoris__VariantProps,
    internalArgProps: Plasmic_9Favoris__ArgProps
  }
);

export default Plasmic_9Favoris;
/* prettier-ignore-end */
